---
language: ruby
cache: bundler
bundler_args: --without benchmarks tools
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
rvm:
  - 2.5.5
  - 2.6.3
  - truffleruby
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    - COVERAGE=true
matrix:
  allow_failures:
    - rvm: truffleruby
  include:
    - rvm: jruby-9.2.7.0
      jdk: openjdk8
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
